# Generated by Django 4.0.5 on 2022-07-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmet',
            old_name='Account',
            new_name='account',
        ),
        migrations.AlterUniqueTogether(
            name='applicationmet',
            unique_together={('account', 'meeting')},
        ),
    ]
